# DATA AUGMENTATION

In [1]:
from keras.preprocessing.image import ImageDataGenerator , array_to_img,img_to_array,load_img

In [2]:
datagen = ImageDataGenerator(rotation_range=40,width_shift_range=0.2,height_shift_range=0.2,shear_range=0.2,zoom_range=0.2,horizontal_flip=True,fill_mode='nearest')

In [3]:
#loading the image

In [4]:
image=load_img('cat_img.jpg')

In [5]:
#converting the image to array

In [6]:
img = img_to_array(image)

In [7]:
print(img)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [8]:
img = img.reshape((1,)+img.shape)

In [9]:
img.shape

(1, 720, 1280, 3)

In [10]:
# the .flow() command generates batches and randomly transforms images and saves them in a directory with the specified format

In [11]:
i=0
for batch in datagen.flow(img,batch_size=1,save_to_dir='output_images',save_prefix='cat',save_format='jpeg'):
    i=i+1
    if i>30:
        break
    